language: python

python:
- '3.7'

matrix:
  include:
    - python: 3.9-dev
      dist: xenial

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

script:
  - flake8
  - coverage run -m pytest
