site_name: 'ğŸ—: `dtyper`: Fix and improve `typer` ğŸ—'

theme:
  name: material

  palette:
    primary:
      'deepPurple'

  font:
    text:
      Roboto
    code:
      Roboto Mono

extra_css: [extra.css]

plugins:
    - mkdocstrings
